# Generated by Django 4.2 on 2026-01-04 16:33

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.CharField(default=management.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='colaboradores/')),
                ('status', models.CharField(choices=[('desligado', 'Desligado'), ('ferias', 'Férias'), ('ativo', 'Ativo')], default='ativo', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_empresa', models.CharField(blank=True, max_length=40, null=True)),
                ('data_admissao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.CharField(default=management.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='setores/')),
                ('dimensao', models.CharField(max_length=100)),
                ('natureza_piso', models.CharField(max_length=100)),
                ('area_envidracada', models.CharField(max_length=100)),
                ('mobilia', models.CharField(choices=[('pouca', 'Pouca'), ('media', 'Média'), ('muita', 'Muita')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.CharField(default=management.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nivel_sujeira', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_previsao_termino', models.DateTimeField()),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaSetor',
            fields=[
                ('id', models.CharField(default=management.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.setor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaColaborador',
            fields=[
                ('id', models.CharField(default=management.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.colaborador')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tarefa')),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='colaboradores',
            field=models.ManyToManyField(related_name='tarefas', through='management.TarefaColaborador', to='management.colaborador'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='setores',
            field=models.ManyToManyField(related_name='tarefas', through='management.TarefaSetor', to='management.setor'),
        ),
    ]
