# Generated by Django 4.2 on 2026-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(default='pt-br', max_length=10)),
                ('fuso_horario', models.CharField(default='America/Fortaleza', max_length=50)),
            ],
        ),
    ]
