# Generated by Django 4.2 on 2026-02-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
