# Generated by Django 4.2 on 2026-02-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_configuracaosistema_email_institucional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='fuso_horario',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='idioma',
        ),
    ]
